/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as GameSettingsRouteImport } from './routes/game-settings'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ChooseRouteImport } from './routes/choose'
import { Route as ArenaRouteRouteImport } from './routes/arena/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaShopRouteImport } from './routes/arena/shop'
import { Route as ArenaProfileRouteImport } from './routes/arena/profile'
import { Route as ArenaLeaderboardRouteImport } from './routes/arena/leaderboard'
import { Route as ArenaLessonsRouteRouteImport } from './routes/arena/lessons/route'
import { Route as ArenaPlaygroundIndexRouteImport } from './routes/arena/playground/index'
import { Route as ArenaLessonsIndexRouteImport } from './routes/arena/lessons/index'
import { Route as ArenaLessonsLessonNameIndexRouteImport } from './routes/arena/lessons/$lessonName/index'
import { Route as ArenaLessonsLessonNameLevelRouteImport } from './routes/arena/lessons/$lessonName/$level'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSettingsRoute = GameSettingsRouteImport.update({
  id: '/game-settings',
  path: '/game-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoute = ChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRouteRoute = ArenaRouteRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaShopRoute = ArenaShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaProfileRoute = ArenaProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaLeaderboardRoute = ArenaLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaLessonsRouteRoute = ArenaLessonsRouteRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaPlaygroundIndexRoute = ArenaPlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaLessonsIndexRoute = ArenaLessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaLessonsRouteRoute,
} as any)
const ArenaLessonsLessonNameIndexRoute =
  ArenaLessonsLessonNameIndexRouteImport.update({
    id: '/$lessonName/',
    path: '/$lessonName/',
    getParentRoute: () => ArenaLessonsRouteRoute,
  } as any)
const ArenaLessonsLessonNameLevelRoute =
  ArenaLessonsLessonNameLevelRouteImport.update({
    id: '/$lessonName/$level',
    path: '/$lessonName/$level',
    getParentRoute: () => ArenaLessonsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/choose': typeof ChooseRoute
  '/components': typeof ComponentsRoute
  '/game-settings': typeof GameSettingsRoute
  '/lobby': typeof LobbyRoute
  '/worlds': typeof WorldsRoute
  '/arena/lessons': typeof ArenaLessonsRouteRouteWithChildren
  '/arena/leaderboard': typeof ArenaLeaderboardRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/shop': typeof ArenaShopRoute
  '/arena/lessons/': typeof ArenaLessonsIndexRoute
  '/arena/playground': typeof ArenaPlaygroundIndexRoute
  '/arena/lessons/$lessonName/$level': typeof ArenaLessonsLessonNameLevelRoute
  '/arena/lessons/$lessonName': typeof ArenaLessonsLessonNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/choose': typeof ChooseRoute
  '/components': typeof ComponentsRoute
  '/game-settings': typeof GameSettingsRoute
  '/lobby': typeof LobbyRoute
  '/worlds': typeof WorldsRoute
  '/arena/leaderboard': typeof ArenaLeaderboardRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/shop': typeof ArenaShopRoute
  '/arena/lessons': typeof ArenaLessonsIndexRoute
  '/arena/playground': typeof ArenaPlaygroundIndexRoute
  '/arena/lessons/$lessonName/$level': typeof ArenaLessonsLessonNameLevelRoute
  '/arena/lessons/$lessonName': typeof ArenaLessonsLessonNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/choose': typeof ChooseRoute
  '/components': typeof ComponentsRoute
  '/game-settings': typeof GameSettingsRoute
  '/lobby': typeof LobbyRoute
  '/worlds': typeof WorldsRoute
  '/arena/lessons': typeof ArenaLessonsRouteRouteWithChildren
  '/arena/leaderboard': typeof ArenaLeaderboardRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/shop': typeof ArenaShopRoute
  '/arena/lessons/': typeof ArenaLessonsIndexRoute
  '/arena/playground/': typeof ArenaPlaygroundIndexRoute
  '/arena/lessons/$lessonName/$level': typeof ArenaLessonsLessonNameLevelRoute
  '/arena/lessons/$lessonName/': typeof ArenaLessonsLessonNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/choose'
    | '/components'
    | '/game-settings'
    | '/lobby'
    | '/worlds'
    | '/arena/lessons'
    | '/arena/leaderboard'
    | '/arena/profile'
    | '/arena/shop'
    | '/arena/lessons/'
    | '/arena/playground'
    | '/arena/lessons/$lessonName/$level'
    | '/arena/lessons/$lessonName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/choose'
    | '/components'
    | '/game-settings'
    | '/lobby'
    | '/worlds'
    | '/arena/leaderboard'
    | '/arena/profile'
    | '/arena/shop'
    | '/arena/lessons'
    | '/arena/playground'
    | '/arena/lessons/$lessonName/$level'
    | '/arena/lessons/$lessonName'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/choose'
    | '/components'
    | '/game-settings'
    | '/lobby'
    | '/worlds'
    | '/arena/lessons'
    | '/arena/leaderboard'
    | '/arena/profile'
    | '/arena/shop'
    | '/arena/lessons/'
    | '/arena/playground/'
    | '/arena/lessons/$lessonName/$level'
    | '/arena/lessons/$lessonName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRouteRoute: typeof ArenaRouteRouteWithChildren
  ChooseRoute: typeof ChooseRoute
  ComponentsRoute: typeof ComponentsRoute
  GameSettingsRoute: typeof GameSettingsRoute
  LobbyRoute: typeof LobbyRoute
  WorldsRoute: typeof WorldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-settings': {
      id: '/game-settings'
      path: '/game-settings'
      fullPath: '/game-settings'
      preLoaderRoute: typeof GameSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose': {
      id: '/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof ChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/shop': {
      id: '/arena/shop'
      path: '/shop'
      fullPath: '/arena/shop'
      preLoaderRoute: typeof ArenaShopRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/profile': {
      id: '/arena/profile'
      path: '/profile'
      fullPath: '/arena/profile'
      preLoaderRoute: typeof ArenaProfileRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/leaderboard': {
      id: '/arena/leaderboard'
      path: '/leaderboard'
      fullPath: '/arena/leaderboard'
      preLoaderRoute: typeof ArenaLeaderboardRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/lessons': {
      id: '/arena/lessons'
      path: '/lessons'
      fullPath: '/arena/lessons'
      preLoaderRoute: typeof ArenaLessonsRouteRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/playground/': {
      id: '/arena/playground/'
      path: '/playground'
      fullPath: '/arena/playground'
      preLoaderRoute: typeof ArenaPlaygroundIndexRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/lessons/': {
      id: '/arena/lessons/'
      path: '/'
      fullPath: '/arena/lessons/'
      preLoaderRoute: typeof ArenaLessonsIndexRouteImport
      parentRoute: typeof ArenaLessonsRouteRoute
    }
    '/arena/lessons/$lessonName/': {
      id: '/arena/lessons/$lessonName/'
      path: '/$lessonName'
      fullPath: '/arena/lessons/$lessonName'
      preLoaderRoute: typeof ArenaLessonsLessonNameIndexRouteImport
      parentRoute: typeof ArenaLessonsRouteRoute
    }
    '/arena/lessons/$lessonName/$level': {
      id: '/arena/lessons/$lessonName/$level'
      path: '/$lessonName/$level'
      fullPath: '/arena/lessons/$lessonName/$level'
      preLoaderRoute: typeof ArenaLessonsLessonNameLevelRouteImport
      parentRoute: typeof ArenaLessonsRouteRoute
    }
  }
}

interface ArenaLessonsRouteRouteChildren {
  ArenaLessonsIndexRoute: typeof ArenaLessonsIndexRoute
  ArenaLessonsLessonNameLevelRoute: typeof ArenaLessonsLessonNameLevelRoute
  ArenaLessonsLessonNameIndexRoute: typeof ArenaLessonsLessonNameIndexRoute
}

const ArenaLessonsRouteRouteChildren: ArenaLessonsRouteRouteChildren = {
  ArenaLessonsIndexRoute: ArenaLessonsIndexRoute,
  ArenaLessonsLessonNameLevelRoute: ArenaLessonsLessonNameLevelRoute,
  ArenaLessonsLessonNameIndexRoute: ArenaLessonsLessonNameIndexRoute,
}

const ArenaLessonsRouteRouteWithChildren =
  ArenaLessonsRouteRoute._addFileChildren(ArenaLessonsRouteRouteChildren)

interface ArenaRouteRouteChildren {
  ArenaLessonsRouteRoute: typeof ArenaLessonsRouteRouteWithChildren
  ArenaLeaderboardRoute: typeof ArenaLeaderboardRoute
  ArenaProfileRoute: typeof ArenaProfileRoute
  ArenaShopRoute: typeof ArenaShopRoute
  ArenaPlaygroundIndexRoute: typeof ArenaPlaygroundIndexRoute
}

const ArenaRouteRouteChildren: ArenaRouteRouteChildren = {
  ArenaLessonsRouteRoute: ArenaLessonsRouteRouteWithChildren,
  ArenaLeaderboardRoute: ArenaLeaderboardRoute,
  ArenaProfileRoute: ArenaProfileRoute,
  ArenaShopRoute: ArenaShopRoute,
  ArenaPlaygroundIndexRoute: ArenaPlaygroundIndexRoute,
}

const ArenaRouteRouteWithChildren = ArenaRouteRoute._addFileChildren(
  ArenaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRouteRoute: ArenaRouteRouteWithChildren,
  ChooseRoute: ChooseRoute,
  ComponentsRoute: ComponentsRoute,
  GameSettingsRoute: GameSettingsRoute,
  LobbyRoute: LobbyRoute,
  WorldsRoute: WorldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
