/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ArenaRouteRouteImport } from './routes/arena/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaLearnRouteImport } from './routes/arena/learn'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRouteRoute = ArenaRouteRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaLearnRoute = ArenaLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => ArenaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/lobby': typeof LobbyRoute
  '/worlds': typeof WorldsRoute
  '/arena/learn': typeof ArenaLearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/lobby': typeof LobbyRoute
  '/worlds': typeof WorldsRoute
  '/arena/learn': typeof ArenaLearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/lobby': typeof LobbyRoute
  '/worlds': typeof WorldsRoute
  '/arena/learn': typeof ArenaLearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/components'
    | '/lobby'
    | '/worlds'
    | '/arena/learn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arena' | '/components' | '/lobby' | '/worlds' | '/arena/learn'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/components'
    | '/lobby'
    | '/worlds'
    | '/arena/learn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRouteRoute: typeof ArenaRouteRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  LobbyRoute: typeof LobbyRoute
  WorldsRoute: typeof WorldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/learn': {
      id: '/arena/learn'
      path: '/learn'
      fullPath: '/arena/learn'
      preLoaderRoute: typeof ArenaLearnRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
  }
}

interface ArenaRouteRouteChildren {
  ArenaLearnRoute: typeof ArenaLearnRoute
}

const ArenaRouteRouteChildren: ArenaRouteRouteChildren = {
  ArenaLearnRoute: ArenaLearnRoute,
}

const ArenaRouteRouteWithChildren = ArenaRouteRoute._addFileChildren(
  ArenaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRouteRoute: ArenaRouteRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  LobbyRoute: LobbyRoute,
  WorldsRoute: WorldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
