/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ChooseRouteImport } from './routes/choose'
import { Route as ArenaRouteRouteImport } from './routes/arena/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultiplayerRoomIdRouteImport } from './routes/multiplayer/$roomId'
import { Route as LobbyRoomIdRouteImport } from './routes/lobby/$roomId'
import { Route as ArenaShopRouteImport } from './routes/arena/shop'
import { Route as ArenaProfileRouteImport } from './routes/arena/profile'
import { Route as ArenaLessonsRouteRouteImport } from './routes/arena/lessons/route'
import { Route as ArenaPlaygroundIndexRouteImport } from './routes/arena/playground/index'
import { Route as ArenaLessonsIndexRouteImport } from './routes/arena/lessons/index'
import { Route as ArenaLeaderboardIndexRouteImport } from './routes/arena/leaderboard/index'
import { Route as ArenaLessonsLessonNameIndexRouteImport } from './routes/arena/lessons/$lessonName/index'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoute = ChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRouteRoute = ArenaRouteRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoomIdRoute = MultiplayerRoomIdRouteImport.update({
  id: '/multiplayer/$roomId',
  path: '/multiplayer/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoomIdRoute = LobbyRoomIdRouteImport.update({
  id: '/lobby/$roomId',
  path: '/lobby/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaShopRoute = ArenaShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaProfileRoute = ArenaProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaLessonsRouteRoute = ArenaLessonsRouteRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaPlaygroundIndexRoute = ArenaPlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaLessonsIndexRoute = ArenaLessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaLessonsRouteRoute,
} as any)
const ArenaLeaderboardIndexRoute = ArenaLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaLessonsLessonNameIndexRoute =
  ArenaLessonsLessonNameIndexRouteImport.update({
    id: '/$lessonName/',
    path: '/$lessonName/',
    getParentRoute: () => ArenaLessonsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/choose': typeof ChooseRoute
  '/components': typeof ComponentsRoute
  '/worlds': typeof WorldsRoute
  '/arena/lessons': typeof ArenaLessonsRouteRouteWithChildren
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/shop': typeof ArenaShopRoute
  '/lobby/$roomId': typeof LobbyRoomIdRoute
  '/multiplayer/$roomId': typeof MultiplayerRoomIdRoute
  '/arena/leaderboard': typeof ArenaLeaderboardIndexRoute
  '/arena/lessons/': typeof ArenaLessonsIndexRoute
  '/arena/playground': typeof ArenaPlaygroundIndexRoute
  '/arena/lessons/$lessonName': typeof ArenaLessonsLessonNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/choose': typeof ChooseRoute
  '/components': typeof ComponentsRoute
  '/worlds': typeof WorldsRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/shop': typeof ArenaShopRoute
  '/lobby/$roomId': typeof LobbyRoomIdRoute
  '/multiplayer/$roomId': typeof MultiplayerRoomIdRoute
  '/arena/leaderboard': typeof ArenaLeaderboardIndexRoute
  '/arena/lessons': typeof ArenaLessonsIndexRoute
  '/arena/playground': typeof ArenaPlaygroundIndexRoute
  '/arena/lessons/$lessonName': typeof ArenaLessonsLessonNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/choose': typeof ChooseRoute
  '/components': typeof ComponentsRoute
  '/worlds': typeof WorldsRoute
  '/arena/lessons': typeof ArenaLessonsRouteRouteWithChildren
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/shop': typeof ArenaShopRoute
  '/lobby/$roomId': typeof LobbyRoomIdRoute
  '/multiplayer/$roomId': typeof MultiplayerRoomIdRoute
  '/arena/leaderboard/': typeof ArenaLeaderboardIndexRoute
  '/arena/lessons/': typeof ArenaLessonsIndexRoute
  '/arena/playground/': typeof ArenaPlaygroundIndexRoute
  '/arena/lessons/$lessonName/': typeof ArenaLessonsLessonNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/choose'
    | '/components'
    | '/worlds'
    | '/arena/lessons'
    | '/arena/profile'
    | '/arena/shop'
    | '/lobby/$roomId'
    | '/multiplayer/$roomId'
    | '/arena/leaderboard'
    | '/arena/lessons/'
    | '/arena/playground'
    | '/arena/lessons/$lessonName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/choose'
    | '/components'
    | '/worlds'
    | '/arena/profile'
    | '/arena/shop'
    | '/lobby/$roomId'
    | '/multiplayer/$roomId'
    | '/arena/leaderboard'
    | '/arena/lessons'
    | '/arena/playground'
    | '/arena/lessons/$lessonName'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/choose'
    | '/components'
    | '/worlds'
    | '/arena/lessons'
    | '/arena/profile'
    | '/arena/shop'
    | '/lobby/$roomId'
    | '/multiplayer/$roomId'
    | '/arena/leaderboard/'
    | '/arena/lessons/'
    | '/arena/playground/'
    | '/arena/lessons/$lessonName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRouteRoute: typeof ArenaRouteRouteWithChildren
  ChooseRoute: typeof ChooseRoute
  ComponentsRoute: typeof ComponentsRoute
  WorldsRoute: typeof WorldsRoute
  LobbyRoomIdRoute: typeof LobbyRoomIdRoute
  MultiplayerRoomIdRoute: typeof MultiplayerRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose': {
      id: '/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof ChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer/$roomId': {
      id: '/multiplayer/$roomId'
      path: '/multiplayer/$roomId'
      fullPath: '/multiplayer/$roomId'
      preLoaderRoute: typeof MultiplayerRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$roomId': {
      id: '/lobby/$roomId'
      path: '/lobby/$roomId'
      fullPath: '/lobby/$roomId'
      preLoaderRoute: typeof LobbyRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/shop': {
      id: '/arena/shop'
      path: '/shop'
      fullPath: '/arena/shop'
      preLoaderRoute: typeof ArenaShopRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/profile': {
      id: '/arena/profile'
      path: '/profile'
      fullPath: '/arena/profile'
      preLoaderRoute: typeof ArenaProfileRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/lessons': {
      id: '/arena/lessons'
      path: '/lessons'
      fullPath: '/arena/lessons'
      preLoaderRoute: typeof ArenaLessonsRouteRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/playground/': {
      id: '/arena/playground/'
      path: '/playground'
      fullPath: '/arena/playground'
      preLoaderRoute: typeof ArenaPlaygroundIndexRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/lessons/': {
      id: '/arena/lessons/'
      path: '/'
      fullPath: '/arena/lessons/'
      preLoaderRoute: typeof ArenaLessonsIndexRouteImport
      parentRoute: typeof ArenaLessonsRouteRoute
    }
    '/arena/leaderboard/': {
      id: '/arena/leaderboard/'
      path: '/leaderboard'
      fullPath: '/arena/leaderboard'
      preLoaderRoute: typeof ArenaLeaderboardIndexRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/lessons/$lessonName/': {
      id: '/arena/lessons/$lessonName/'
      path: '/$lessonName'
      fullPath: '/arena/lessons/$lessonName'
      preLoaderRoute: typeof ArenaLessonsLessonNameIndexRouteImport
      parentRoute: typeof ArenaLessonsRouteRoute
    }
  }
}

interface ArenaLessonsRouteRouteChildren {
  ArenaLessonsIndexRoute: typeof ArenaLessonsIndexRoute
  ArenaLessonsLessonNameIndexRoute: typeof ArenaLessonsLessonNameIndexRoute
}

const ArenaLessonsRouteRouteChildren: ArenaLessonsRouteRouteChildren = {
  ArenaLessonsIndexRoute: ArenaLessonsIndexRoute,
  ArenaLessonsLessonNameIndexRoute: ArenaLessonsLessonNameIndexRoute,
}

const ArenaLessonsRouteRouteWithChildren =
  ArenaLessonsRouteRoute._addFileChildren(ArenaLessonsRouteRouteChildren)

interface ArenaRouteRouteChildren {
  ArenaLessonsRouteRoute: typeof ArenaLessonsRouteRouteWithChildren
  ArenaProfileRoute: typeof ArenaProfileRoute
  ArenaShopRoute: typeof ArenaShopRoute
  ArenaLeaderboardIndexRoute: typeof ArenaLeaderboardIndexRoute
  ArenaPlaygroundIndexRoute: typeof ArenaPlaygroundIndexRoute
}

const ArenaRouteRouteChildren: ArenaRouteRouteChildren = {
  ArenaLessonsRouteRoute: ArenaLessonsRouteRouteWithChildren,
  ArenaProfileRoute: ArenaProfileRoute,
  ArenaShopRoute: ArenaShopRoute,
  ArenaLeaderboardIndexRoute: ArenaLeaderboardIndexRoute,
  ArenaPlaygroundIndexRoute: ArenaPlaygroundIndexRoute,
}

const ArenaRouteRouteWithChildren = ArenaRouteRoute._addFileChildren(
  ArenaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRouteRoute: ArenaRouteRouteWithChildren,
  ChooseRoute: ChooseRoute,
  ComponentsRoute: ComponentsRoute,
  WorldsRoute: WorldsRoute,
  LobbyRoomIdRoute: LobbyRoomIdRoute,
  MultiplayerRoomIdRoute: MultiplayerRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
